unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

set -a terminal-features "tmux-256color:RGB"
set -g base-index 1
set -g renumber-windows on
set -g status-position top
set -g status-justify absolute-centre
set -g status-style 'bg=black'
set -g window-status-current-style "fg=black bg=white"
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""
set -g mouse on
set -g default-command "${SHELL}"

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

set-window-option -g mode-keys vi
bind -n PageUp copy-mode -u
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded!"
bind b set -g status
