#--------------------------------
# Shadows

shadow = false;
# shadow-radius = 20;
# shadow-offset-x = -20;
# shadow-offset-y = -20;
# shadow-opacity = 1; # Range: 0.0 - 1.0
# shadow-color = "#000000";
# crop-shadow-to-monitor = false;

#--------------------------------
# Fading

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 3
no-fading-openclose = true
no-fading-destroyed-argb = false

#--------------------------------
# Animations

animations = ({
	triggers = [ "open", "show" ];
	preset = "appear";
    duration = .1;
}, {
    triggers = ["close", "hide"];
    preset = "disappear"
    duration = .2;
})

#--------------------------------
# Transparency / Opacity

frame-opacity = 1;
inactive-dim-fixed = true;

#--------------------------------
# Corners

corner-radius = 12

#--------------------------------
# Blur

blur: {
    method = "dual_kawase";
    size = 10
    deviation = 4;
    strength = 6;
    background = true;
    background-frame = false;
    background-fixed = true;
}

#--------------------------------
# General Settings

dbus = false
daemon = true
backend = "glx" #backends: `xrender`, `glx`, or `egl`.
dithered-present = false
vsync = true;
detect-rounded-corners = true
detect-client-opacity = true
use-ewmh-active-win = true
unredir-if-possible = false
unredir-if-possible-delay = 0
detect-transient = true
detect-client-leader = false
use-damage = true
xrender-sync-fence = false
force-win-blend = false
no-ewmh-fullscreen = false
max-brightness = 1.0
transparent-clipping = false # shows the background for transparent window.

log-level = "warn"; # possible_values: "trace", "debug", "info", "warn", "error"
# write-pid-path = "/path/to/your/log/file"

rules: (
    { match = "focused"; opacity = 1; },
	{ match = "!focused"; opacity = 0.85; },
	{ match = "tooltip"; fade = true; shadow = true; opacity = 0.5; focus = true; full-shadow = false; },
	{ match = "popup_menu"; opacity = 0.7; },
	{ match = "class_g = 'Polybar'"; blur-background = false; opacity = 1; corner-radius = 0; },
	# { match = "dropdown_menu"; opacity = 0.7; },)
	# { match = "tooltip"; fade = false; shadow = false; full-shadow = false; },
)

