# Nightfox Alacritty Colors
## name: carbonfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/carbonfox/alacritty.toml

[colors.primary]
background = "#070707"
foreground = "#ffffff"
dim_foreground = "#a2a2a7"
bright_foreground = "#ffffff"

[colors.normal]
black = "#070707"
red = "#ff4f44"
green = "#3ce155"
yellow = "#ffe014"
blue = "#148eff"
magenta = "#cc65ff"
cyan = "#5acdfa"
white = "#ffffff"

[window]
# opacity = 0.8

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12
